cab/models.py
from django.db import models
from django.contrib.auth.models import User
from pygments import lexers,formatters,highlight,lexers
from tagging.fields import TagField
from markdown import markdown
import datetime
from cab import managers

# Create your models here.

class Language(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    language_code = models.CharField(max_length=50)
    mime_type = models.CharField(max_length=100)
    objects = managers.LanguageManager()

    class Meta:
        ordering=['name']

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return ('cab_language_detail',(),{'slug':self.slug})

    get_absolute_url = models.permalink(get_absolute_url)

    def get_lexer(self):
        return lexers.get_lexer_by_name(self.language_code)

class Snippet(models.Model):
    title = models.CharField(max_length=255)
    language = models.ForeignKey(Language)
    author = models.ForeignKey(User)
    description = models.TextField()
    description_html = models.TextField(editable=False)
    code = models.TextField()
    highlighted_code = models.TextField(editable=False)
    tags = TagField()
    pub_date = models.DateTimeField(editable=False)
    updated_date = models.DateTimeField(editable=False)
    objects = managers.SnippetManager()

    class Meta:
        ordering = ['-pub_date']

    def __unicode__(self):
        return self.title
    
    def highlight(self):
        return highlight(self.code,self.language.get_lexer(),formatters.HtmlFormatter(lineons=True))

    def save(self,force_insert=False,force_update=False):
        if not self.id:
            self.pub_date = datetime.datetime.now()
        self.updated_date = datetime.datetime.now()
        self.description_html = markdown(self.description)
        self.highlighted_code = self.highlight()
        super(Snippet,self).save(force_insert,force_update)

    def get_absolute_url(self):
        return ('cab_snippet_detail',(),{'object_id':self.id })

    get_absolute_url = models.permalink(get_absolute_url)

	
class Bookmark(models.Model):
    snippet = models.ForeignKey(Snippet)
    user = models.ForeignKey(User,related_name='cab_bookmark')
    date =  models.DateTimeField(editable=False)

    class Meta:
        ordering  =['-date']

    def __unicode__(self):
        return "%s bookmarked by %s" (self.snippet,self.user)

    def save(self):
        if not self.id:
            self.date = datetime.datetime.now()
        super(Bookmark,self).save()

    

cab/views/signup.py
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from cab.forms import SignupForm
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def signup(request):
	if request.method == 'POST':
		form = SignupForm(data=request.POST)
		if form.is_valid():
			new_user = form.save()
			return HttpResponseRedirect("/admin")
	else:
		form = SignupForm()
	return render_to_response('cab/signup.html',{'form':form})

cab/views/snippets.py
from django.http import HttpResponseRedirect,HttpResponseForbidden
from django.shortcuts import render_to_response,get_object_or_404
from django.contrib.auth.decorators import login_required 
# from cab.forms import AddSnippetForm
from cab.models import Snippet
from django.forms import ModelForm
from django.core.context_processors import csrf
# from django.views.decorators.csrf import csrf_exempt
from django.template import RequestContext

class SnippetForm(ModelForm):
	class Meta:
		model = Snippet
		exclude = ['author']

# @csrf_exempt
def add_snippet(request):
	if request.method == 'POST':
		form = SnippetForm(data=request.POST)
		if form.is_valid():
			new_snippet = form.save(commit=False)
			new_snippet.author = request.user
			new_snippet.save()
			return HttpResponseRedirect(new_snippet.get_absolute_url())
	else:
		form = SnippetForm()
	return render_to_response('cab/snippet_form.html',
								{'form':form,'add':True},context_instance=RequestContext(request,processors=[csrf]))

add_snippet = login_required(add_snippet)


def edit_snippet(request,snippet_id):
	snippet = get_object_or_404(Snippet,pk=snippet_id)
	if request.user.id != snippet.author.id:
		return HttpResponseForbidden()
	if request.method == 'POST':
		form = SnippetForm(instance=snippet,data=request.POST)
		if form.is_valid():
			snippet = form.save()
			return HttpResponseRedirect(snippet.get_absolute_url())
	else:
		form = SnippetForm(instance=snippet)
	return render_to_response('cab/snippet_form.html',
								{'form':form,'add':False},context_instance=RequestContext(request,processors=[csrf]))
edit_snippet = login_required(edit_snippet)

cab/templates/cab/language_detail.html
<html>
<head>
<title>Language detail</title>
</head>
<body>
	{% if not object_list %}
	<p>No snippets belongs to this language!</p>
	{% endif %}
	{% for object in object_list  %}
		<b>{{ object.title  }}</b>
		<p>{{ object.description  }}</p>
		<p>{{ object.language  }}</p>
		<p>
		{% autoescape off %}
		{{ object.highlighted_code  }}
		{% endautoescape %}
		</p>
		<p>{{ object.pub_date|date:"Y-m-d" }}</p>
		<p>{{ object.updated_date|date:"Y-m-d" }}</p>
		<p><a href="{{ object.get_absolute_url }}">代码详细</a></p>
	{% endfor  %}
	
	<p>Page-{{page}}
	{% if page.has_previous  %}
	<a href ="?page={{ page.pervious_page_number }}">Previous pages</a>
	{% endif  %}
	{% if page.has_next_page %}
	<a href="?page={{ page.next_page_number }}">Netx page</a>
	{% endif %}</p>


</body>
</html>          

cab/templates/cab/language_list.html
<html>
<head>
<title>Language List</title>
</head>
<body>
	{% for object in object_list  %}
		<h5>{{ object.name  }}</h5>
		<p>{{ object.slug  }}</p>
		<p>{{ object.language_code  }}</p>
		<p>{{ object.mime_type }}</p>
		<p><a href="{{ object.get_absolute_url }}">Language detail</a></p>
	{% endfor  %}
	
	<p>Page-{{page}}
	{% if page.has_previous  %}
	<a href ="?page={{ page.pervious_page_number }}">Previous pages</a>
	{% endif  %}
	{% if page.has_next_page %}
	<a href="?page={{ page.next_page_number }}">Netx page</a>
	{% endif %}</p>


</body>
</html>          

cab/templates/cab/signup.html
<html>
<head>
	<title>Sign up for an account</title>
</head>
<body>
	<h1>Sign up for an account</h1>
	<p>Use the form below to register for your new account;all fields are required.</p>
	<form method="post" action="">{% csrf_token%}
		{% if form.non_field_errors %}
		<p><span class="error">
		{{ form.non_field_errors|join:","}}
		</span></p>
		{% endif %}
		<p>{% if form.username.errors %}
			<span class="error">{{ form.username.errors|join:","}}</span>
		{% endif %}	</p>
		<p><label for="id_username">Username:</label>
			{{ form.username }}</p>
		<p>{%if form.email.errors %}
		<span class="error">
		{{ form.email.errors|join:","}}
		</span>
		{% endif %}</p>
		<p><label for="id_name">Your e-mail address:</label>
			{{ form.email }}</p>
		<p>{% if form.password1.errors %}
			<span class="error">
				{{ form.password1.errors|join:","}}
			</span>
			{% endif %}</p>
		<p><label for="id_password1">Password:<label>
			{{ form.password1 }}</p>
		<p>{% if form.password2.errors %}
			<span class="error">
				{{form.password2.errors|join:","}}
			</span>
			{% endif %}</p>
			<p><label for="id_password2">Password(again,to catch typos):</label>
				{{ form.password2 }}</p>
			<p><input type="submit" value="Submit"></p>
		</form>
	</body>
</html>

cab/templates/cab/snippet_detail.html
<html>
<head>
<title>Snippet Detail</title>
</head>
<body>
	{% if object %}
		<p>{{ object.title  }}</p>
		<p>{{ object.description  }}</p>
		<p>{{ object.language  }}</p>
		<p>
		{% autoescape off %}
		{{ object.highlighted_code  }}
		{% endautoescape %}
		</p>
		<p>{{ object.pub_date }}</p>
		<p>{{ object.updated_date }}</p>
	{% endif %}
	
	<p>{{page}};
	{% if page.has_previous  %}
	<a href ="?page={{ page.pervious_page_number }}">Previous pages</a>
	{% endif  %}
	{% if page.has_next_page %}
	<a href="?page={{ page.next_page_number }}">Netx page</a>
	{% endif %}</p>

</body>
</html>        

cab/templates/cab/snippet_form.html
<html>
<head>
	<title>{% if add %}Add a snippet{% else %}Edit a snippet{% endif %}</title>
</head>
<body>
	<h1>{% if add %}Add a snippet{% else %}Edit a snippet{% endif %}</h1>
	<p>Use the form below to your snippet;all fields are required.</p>
	<form method = "post" action="">{% csrf_token %}

		{{ form.as_ul }}
	<!-- <p>{% if form.title.errors %}
	<span class="error"> 
		{{ form.title.errors|join:", "}}
	</span>
	{% endif  %}</p>
	<p><label for="id_title">Title:</label>
		{{ form.title}}</p>

	<p>{% if form.language.errors %}
	<span class="error"> 
		{{ form.language.errors|join:", "}}
	</span>
	{% endif  %}</p>
	<p><label for="id_language">Language:</label>
		{{ form.language}}</p>

	<p>{% if form.description.errors %}
	<span class="error"> 
		{{ form.description.errors|join:", "}}
	</span>
	{% endif  %}</p>
	<p><label for="id_description">Description:</label>
		{{ form.description}}</p>

	<p>{% if form.code.errors %}
	<span class="error"> 
		{{ form.code.errors|join:", "}}
	</span>
	{% endif  %}</p>
	<p><label for="id_code">Code:</label>
		{{ form.code}}</p>

	<p>{% if form.tags.errors %}
	<span class="error"> 
		{{ form.tags.errors|join:", "}}
	</span>
	{% endif  %}</p>
	<p><label for="id_tags">Tags:</label>
		{{ form.tags}}</p>-->
	<p><input type="submit" value="Submit"></p> 
	</form>
</body>
</html>

cab/templates/cab/snippet_list.html
<html>
<head>
<title>Snippet List</title>
</head>
<body>
	{% for object in object_list  %}
		<p>{{ object.title  }}</p>
		<p>{{ object.lauguage  }}</p>
		<p>{{ object.description  }}</p>
		<p>{{ object.pub_date  }}</p>
		<p>{{ object.updated_date }}</p>
	{% endfor  %}
	
	<p>{{page}};
	{% if page.has_previous  %}
	<a href ="?page={{ page.pervious_page_number }}">Previous pages</a>
	{% endif  %}
	{% if page.has_next_page %}
	<a href="?page={{ page.next_page_number }}">Netx page</a>
	{% endif %}</p>


</body>
</html>          

cab/templates/cab/top_authors.html
<html>
<head>
	<title>Top Authors</title>
</head>
<body>
	<h2>Top Authors List</h2>
	{% if object_list %}
	<p>author exsit test.</p>
		{% for author in object_list %}
			<p>{{ author }}</p>
		{% endfor %}
	{% else %}
		<p>No objects<p>
	{% endif %}
</body>
</html>

cab/templates/cab/top_language.html
<html>
<head>
<title>Language detail</title>
</head>
<body>
	{% for object in object_list  %}
		<b>{{ object.title  }}</b>
		<p>{{ object.description  }}</p>
		<p>{{ object.language  }}</p>
		<p>
		{% autoescape off %}
		{{ object.highlighted_code  }}
		{% endautoescape %}
		</p>
		<p>{{ object.pub_date|date:"Y-m-d" }}</p>
		<p>{{ object.updated_date|date:"Y-m-d" }}</p>
		<p><a href="{{ object.get_absolute_url }}">代码详细</a></p>
	{% endfor  %}
	
	<p>Page-{{page}}
	{% if page.has_previous  %}
	<a href ="?page={{ page.pervious_page_number }}">Previous pages</a>
	{% endif  %}
	{% if page.has_next_page %}
	<a href="?page={{ page.next_page_number }}">Netx page</a>
	{% endif %}</p>


</body>
</html>          