rent/urls.py
from django.conf.urls.defaults import *
# from rent.views import *
# from django.contrib.auth.views import login,logout
from django.conf import settings

urlpatterns = patterns('rent.views',

    (r'^$','contact_list'),
    (r'^contract/$','contact_list'),
	url(r'^contract/id=(?P<id>\d)/$','contact_detail',name='contract_detail'),
    (r'^pay_records/$','pay_records_list'),
    (r'^pay_record/id=(?P<id>\d+)/$','pay_record_detail','pay_record_detail'),

    (r'^contract/search_con/$','search_contract'),
    (r'^contract/search_con/?name=(?P<name>[-\w]+)/$','search_contract'),

    (r'^pay_records/search_pr/$','search_pay_record'),
    (r'^pay_records/search_pr/?name=(?P<name>[-\w]+)/$','search_pay_record'),
    url(r'^add_contract/$','add_contract',name='rent_contract_add'),
    url(r'^edit_contract/(?P<contract_id>\d+)/$','edit_contract',name='rent_contract_edit'),
    url(r'^add_pr/(?P<contract_id>\d+)/$','add_pr',name='rent_pr_add'),
    url(r'^edit_pr/(?P<pr_id>\d+)/$','edit_pr',name='rent_pr_edit'),
    url(r'^delete_pr/(?P<pr_id>\d+)/$','delete_pr',name='rent_pr_delete'),
)

urlpatterns += patterns('',

	url(r'^login/$','django.contrib.auth.views.login'),
	url(r'^logout/$','django.contrib.auth.views.logout',{'template_name':'registration/logout.html'}),
)


rent/models.py
#coding=utf-8
from django.db import models
import datetime
# Create your models here.

class Contract(models.Model):

	LIVE_STATUS = 1
	END_STATUS = 0
	FLAG_CHOICES = (
		(LIVE_STATUS,'正常'),
		(END_STATUS,'到期'),
		)

	client = models.CharField(max_length=20,verbose_name='客户')
	contract_num = models.CharField(max_length=20,verbose_name='合同编号')
	begin_date = models.DateField(verbose_name='租约开始日期')
	end_date = models.DateField(verbose_name='租约结束日期')
	month_pay = models.DecimalField(max_digits=7,decimal_places=2,verbose_name='月租金')
	flag = models.IntegerField(choices=FLAG_CHOICES,default=LIVE_STATUS,verbose_name='合同状态')

	def __unicode__(self):
		return "%s:%s:%s" % (self.contract_num,self.client,self.flag)

	@models.permalink
	def get_absolute_url(self):
		return ('contract_detail',(),{'id':self.id})


class Pr(models.Model):
	contract = models.ForeignKey(Contract,verbose_name='合同信息')
	pay_date = models.DateField(default=datetime.datetime.now,verbose_name='缴费日期')
	pay_value = models.DecimalField(max_digits=7,decimal_places=2,verbose_name='缴费金额')

	class Meta:
		ordering = ['-pay_date']

	def __unicode__(self):
		return "%s:%s:%s:%s" % (self.contract.contract_num,self.contract.client,self.pay_date,self.pay_value)

	@models.permalink
	def get_absolute_url(self):
		return ('pay_record_detail',(),{'id':self.id})

rent/views.py
from django.shortcuts import render_to_response,get_object_or_404
from django.http import HttpResponseRedirect
from rent.models import Pr,Contract
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.forms import ModelForm
from django.core.context_processors import csrf 

#ContractForm++++++++++++++++++++++++++++++++
class ContractForm(ModelForm):
	class Meta:
		model = Contract

@login_required
def add_contract(request):
	if request.method == 'POST':
		form = ContractForm(data=request.POST)
		if form.is_valid():
			new_contract = form.save()
			return HttpResponseRedirect(new_contract.get_absolute_url())
	else:
		form = ContractForm()
	return render_to_response('rent/contract_form.html',{'form':form,'add':True},context_instance=RequestContext(request,processors=[csrf]))

@login_required
def edit_contract(request,contract_id):
	contract = get_object_or_404(Contract,pk=contract_id)
	if request.method == 'POST':
		form = ContractForm(instance=contract,data=request.POST)
		if form.is_valid():
			contract = form.save()
			return HttpResponseRedirect(contract.get_absolute_url())
	else:
		form = ContractForm(instance=contract)
	return render_to_response('rent/contract_form.html',{'form':form,'add':False},context_instance=RequestContext(request,processors=[csrf]))

#ConrtactForm End++++++++++++++++++++++++++++++++


#PrForm++++++++++++++++++++++++++++++++++++++++++
class PrForm(ModelForm):
	class Meta:
		model = Pr

@login_required
def add_pr(request,contract_id):
	if request.method == 'POST':
		form = PrForm(data=request.POST)
		if form.is_valid():
			new_pr = form.save()
			new_pr.save()
			return HttpResponseRedirect(new_pr.contract.get_absolute_url())
	else:
		contract = get_object_or_404(Contract,pk=contract_id)
		form = PrForm(initial={'contract':contract})
	return render_to_response('rent/pr_form.html',{'form':form,'add':True},context_instance=RequestContext(request,processors=[csrf]))

@login_required
def edit_pr(request,pr_id):
	pr = get_object_or_404(Pr,pk=pr_id)
	if request.method == 'POST':
		form = PrForm(instance=pr,data=request.POST)
		if form.is_valid():
			pr = form.save()
			return HttpResponseRedirect(pr.contract.get_absolute_url())
	else:
		form = PrForm(instance=pr)
	return render_to_response('rent/pr_form.html',{'form':form,'add':False},context_instance=RequestContext(request,processors=[csrf]))

@login_required
def delete_pr(request,pr_id):
	pr = get_object_or_404(Pr,pk=pr_id)
	contract = pr.contract
	if request.method == 'POST':
		if request.POST['del_pr'] == 'yes':
			pr.delete()
		elif request.POST['del_pr'] == 'no':
			pass
		return HttpResponseRedirect(contract.get_absolute_url())
	else:
		pass# return HttpResponseRedirect(contract.get_absolute_url())
	return render_to_response('rent/pr_delete_confirm.html',{'pr':pr},context_instance=RequestContext(request,processors=[csrf]))
#PrForm End++++++++++++++++++++++++++++++++++++++

@login_required
def contact_list(request):
	contract_list = Contract.objects.all()
	return render_to_response('rent/contract_list.html',{'contract_list':contract_list},context_instance=RequestContext(request))



@login_required
def contact_detail(request,id):
	contract_detail = get_object_or_404(Contract,pk=id)
	pr_list = Pr.objects.filter(contract=id)
	return render_to_response('rent/contract_detail.html',
							  {'contract':contract_detail,
							   'pr_list':pr_list},
							  context_instance=RequestContext(request)
							  )
@login_required
def pay_records_list(request):
	records_list = Pr.objects.all()
	return render_to_response('rent/pay_records_list.html',{'record_list':records_list},context_instance=RequestContext(request))

@login_required
def pay_record_detail(request,id):
	record_detail = get_object_or_404(pd==id)
	return render_to_response('rent/pay_record_detail',{'record_detail':record_detail},context_instance=RequestContext(request))

@login_required
def search_contract(request):
	query = request.GET.get('name','')
	results = []
	if query:
		results = Contract.objects.filter(client__icontains=query)
	return render_to_response('rent/search_contract.html',{'query':query,
								  'results':results},context_instance=RequestContext(request))

@login_required	
def search_pay_record(request):
	query = request.GET.get('name','')
	results = []
	if query:
		results = Pr.objects.filter(contract__client__icontains=query)
	return render_to_response('rent/search_pr.html',{'query':query,
								'results':results},context_instance=RequestContext(request))

rent/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link href="/static/bootstrap.min.css" rel="stylesheet" type="text/css" />
	</head>
	<body>
		<div class="container">
		<div id="header" class="navbar navbar-inverse" >
			{% block header %}
				{% if user.is_authenticated %}
				<p>当前操作者:{{ user.username }}
					<a href="/rent/logout">退出</a></p>
				{% endif %}
			{% endblock %}
		</div>
		
			<div id="menu">
				{% block menu %}
				<ul class="nav nav-pills">
						<li><a href="/rent/contract">合同列表</a></li>
						<li><a href="/rent/pay_records/">缴费列表</a></li>
						<li><a href="/rent/add_contract/">新增合同</a></li>
				</ul>
				{% endblock %}
			</div>
			{% block search_bar %}
			{% endblock %}
			<div id="content">	
			{%  block content %}
			{% endblock %}
			</div>
		</div>
		{% block footer %}
			<div id="footer">
				<div class="container">
					<p class="muted credit">2012 @ EE</p>
				</div>
			</div>
		{% endblock%}
	</body>
</html>

rent/templates/rent/contract_detail.html
{% extends "base.html" %}

	{% block title %}合同信息{% endblock %}

{% block content %}
	<div class="contract_detail">
		{% if contract %}
		<h3>合同信息</h3>
		<table class="table table-bordered">
			<thead>
				<th>租户姓名：</th>
				<th>合同编号：</th>
				<th>租约起始日期：</th>
				<th>租约终止日期：</th>
				<th>月租金：</th>
				<th>合同状态：</th>
			</thead>
			<tr>
				<td>{{ contract.client }}</td>
				<td>{{ contract.contract_num }}</td>
				<td>{{ contract.begin_date|date:"Y-m-d" }}</td>
				<td>{{ contract.end_date|date:"Y-m-d" }}</td>
				<td>{{ contract.month_pay }}</td>
				<td>{{ contract.flag }}</td>
			</tr>
		</table>
		<a href="/rent/edit_contract/{{ contract.id }}" class="btn btn-primary">编辑合同</a>
		{% endif %}
	</div>

	<div class="pr_list">
		<h3>缴费记录</h3>
		{% if pr_list %}
		<table class="table table-bordered table-striped table-hover">
			<thead>
					<th>缴费日期</th>
					<th>缴费数额</th>
			</thead>
			{% for pr in pr_list %}
			<tr>
			 <td>{{ pr.pay_date|date:"Y-m-d" }}</td>
			 <td>{{ pr.pay_value}}</td>
			 <td><a href="/rent/edit_pr/{{ pr.id }}" >修改</a></td>
			 <td><a href="/rent/delete_pr/{{ pr.id }}" >删除</a></td>
			</tr>
			{% endfor %}
		</table>
		{% else %}
			<p class="alert">无缴费记录！</p>
		{% endif %}
		<p><a href="/rent/add_pr/{{ contract.id }}" class="btn btn-primary">新增缴费记录</a></p>
	</div>
{% endblock %}

rent/templates/rent/contract_form.html
{% extends "base.html" %}
  {% block title %}
    {% if add %}添加{% else %}编辑{% endif %}合同
  {% endblock %}

  {% block content %}
    <h3>{% if add %}添加{% else %}编辑{% endif %}合同</h3>
    <span class="help-block">使用表单{% if add %}添加{% else %}编辑{% endif %}合同；所有字段都是必填选项。</span>
    <form method="post" action="">
      {% csrf_token %}
      {{ form.as_p}}
      <!-- <p>{% if form.client.errors %}
      <span class="error">
      {{ form.client.errors|join:", " }}
      </span>
      {% endif %}</p>
      <p><label for="id_title">客户名:</label> 
      {{ form.client }}</p>
      <p>{% if form.contract_num.errors %}
      <span class="error">
      {{ form.contract_num.errors|join:", " }}
      </span>
      {% endif %}</p>
      <p><label for="id_contracts">合同编号:</label>
      {{ form.contract_num }}</p>
      <p>{% if form.begin_date.errors %}
      <span class="error">
      {{ form.begin_date.errors|join:", " }}
      </span>
      {% endif %}</p>
      <p><label for="id_begin_date">租约开始日期:</label>
      {{ form.begin_date }}</p>
      <p>{% if form.end_date.errors %}
      <span class="error">
      {{ form.end_date.errors|join:", " }}
      </span>
      {% endif %}</p>
      <p><label for="id_end_date">租约结束日期:</label>
      {{ form.end_date }}</p>
      <p>{% if form.month_pay.errors %}
      <span class="error">
      {{ form.month_pay.errors|join:", " }}
      </span>
      {% endif %}</p>
      <p><label for="id_month_pay">月租金额:</label>
     {{ form.month_pay }}</p>
     <p>{% if form.flag.errors %}
      <span class="error">
      {{ form.flag.errors|join:", " }}
      </span>
      {% endif %}</p>
      <p><label for="id_flag">合同状态:</label>
     {{ form.flag }}</p> -->
      <input class="btn btn-primary" type="submit" value="{% if add %}添加{% else %}编辑{% endif %}"><a href="/rent" class="btn">取消</a>
    </form>
{% endblock%}

rent/templates/rent/contract_list.html
{% extends "base.html" %}
{% block title %}合同列表{% endblock %}
	{% block search_bar %}
		<form method="get" action="search_con/" class="form-search">
			<input type="text" name="name" placeholder="按客户名搜索合同" class="input-media search-query"/>
			<input type="submit" value="提交" class="btn"/>
		</form>
	{% endblock  %}
{% block content %}

<table class="table table-bordered table-striped table-hover">
	<thead>
		<thead>
			<th>合同编号</th>
			<th>租户姓名</th>
			<th>租约起始时间</th>
			<th>租约终止时间</th>
			<th>月租金</th>
			<th>合同状态</th>
		</thead>
	</thead>
{% for contract in contract_list %}
	<tr>
		<td><a href="{{ contract.get_absolute_url }}">{{ contract.contract_num }}</td>
		<td>{{ contract.client }}</a> </td>
		<td>{{ contract.begin_date|date:"Y-m-d" }}</td>
		<td>{{ contract.end_date|date:"Y-m-d" }}</td>
		<td>{{ contract.month_pay }}</td>
		<td>{{ contract.flag }}</td>
	</tr>
{% endfor %}
</table>
{% endblock %}

rent/templates/rent/pay_records_list.html
{% extends "base.html" %}
{% block title %}缴费记录列表{% endblock %}
	{% block search_bar %}
		<form method="get" action="search_pr/" class="form-search">
			<input type="text" name="name" id="" placeholder="按客户名搜索缴费记录" class="input-media search-query" />
			<input type="submit" value="提交" class="btn" />
		</form>
	{% endblock  %}
{% block content %}
<table class="table table-bordered table-striped table-hover">
	<thead>
		<tr>
			<th>缴费时间</th>
			<th>租户姓名</th>
			<th>缴费金额</th>
			<th>所属合同编号</th>
			<th>租约起始时间</th>
			<th>租约终止时间</th>
		</tr>
	</thead>
{% for record in record_list %}
	<tr>
		<td>{{ record.pay_date|date:"Y-m-d" }}</td>
		<td>{{ record.contract.client }}</a> </td>
		<td>{{ record.pay_value}}</td>
		<td><a href="{{ record.contract.get_absolute_url }}">{{ record.contract.contract_num }}</td>
		<td>{{ record.contract.begin_date|date:"Y-m-d" }}</td>
		<td>{{ record.contract.end_date|date:"Y-m-d" }}</td>
	</tr>
{% endfor %}
</table>
{% endblock %}

rent/templates/rent/pr_delete_confirm.html
{% extends "base.html" %}

{% block title %}确认删除记录{% endblock %}

{% block content %}
	{% if pr %}
	<h3>缴费记录</h3>
	<table class="table table-bordered table-striped table-hover">
		<thead>
			<th>合同信息</th>
			<th>缴费日期</th>
			<th>缴费金额</th>
		</thead>
		<tbody>
		<tr>
			<td>{{ pr.contract }}</td>
			<td>{{ pr.pay_date|date:"Y-m-d" }}</td>
			<td>{{ pr.pay_value}}</td>
		</tr>
		<tbody>
	</table>
	<span class="label label-warning">确定要删除该条缴费记录么？</span>
	{% endif %}

	<form method="post" action="">
		{% csrf_token %}
		<label class="radio"><input type="radio" name="del_pr" value="yes" id="del_pr_confirm1" checked />是</label>
		<label class="radio"><input type="radio" name="del_pr" value="no" id="del_pr_confirm2 "/>否</label>
		<p><input type="submit" value="确定" class="btn"></p>
	</form>
{% endblock %}

rent/templates/rent/pr_form.html
{% extends "base.html" %}

{% block title %}
  {% if add %}添加{% else %}编辑{% endif %}缴费记录
{% endblock %}

{% block content %}
    <h3>{% if add %}添加{% else %}编辑{% endif %}缴费记录</h3>
    <span class="help-block">使用表单{% if add %}添加{% else %}编辑{% endif %}缴费记录缴费记录；所有字段都是必填选项。</span>
    <form method="post" action="" >
      {% csrf_token %}
      {{ form.as_p}}
      <!-- <p>{% if form.client.errors %}
      <span class="error">
      {{ form.client.errors|join:", " }}
      </span>
      {% endif %}</p>
      <p><label for="id_title">客户名:</label> 
      {{ form.client }}</p>
      <p>{% if form.contract_num.errors %}
      <span class="error">
      {{ form.contract_num.errors|join:", " }}
      </span>
      {% endif %}</p>
      <p><label for="id_contracts">合同编号:</label>
      {{ form.contract_num }}</p>
      <p>{% if form.begin_date.errors %}
      <span class="error">
      {{ form.begin_date.errors|join:", " }}
      </span>
      {% endif %}</p>
      <p><label for="id_begin_date">租约开始日期:</label>
      {{ form.begin_date }}</p>
      <p>{% if form.end_date.errors %}
      <span class="error">
      {{ form.end_date.errors|join:", " }}
      </span>
      {% endif %}</p>
      <p><label for="id_end_date">租约结束日期:</label>
      {{ form.end_date }}</p>
      <p>{% if form.month_pay.errors %}
      <span class="error">
      {{ form.month_pay.errors|join:", " }}
      </span>
      {% endif %}</p>
      <p><label for="id_month_pay">月租金额:</label>
     {{ form.month_pay }}</p>
     <p>{% if form.flag.errors %}
      <span class="error">
      {{ form.flag.errors|join:", " }}
      </span>
      {% endif %}</p>
      <p><label for="id_flag">合同状态:</label>
     {{ form.flag }}</p> -->
      <p><input type="submit" value="{% if add %}添加{% else %}编辑{% endif %}" class="btn btn-primary"><a href=""></a></p>
    </form>
{% endblock %}

rent/templates/rent/search_contract.html
{% extends "base.html" %}
{% block title %}搜索合同 {% endblock %}

	{% block search_bar %}
		<form method="get" action="" class="form-search">
				<input type="text" name="name" id="" placeholder="按客户名搜索合同" class="meida search-query"/>
				<input type="submit" value="提交" class="btn" />
		</form>
	{% endblock  %}
{% block content%}

		{% if results %}
			<span class="help-block">搜索了包含"{{ query }}"的客户名;结果列表如下。</span>
			<table class="table table-bordered table-striped table-hover">
				<thead>
					<th>合同编号</th>
					<th>租户姓名</th>
					<th>租约起始时间</th>
					<th>租约终止时间</th>
					<th>月租金</th>
					<th>合同状态</th>
				</thead>
				{% for contract in results %}
				<tr>
					<td><a href="{{ contract.get_absolute_url }}">{{ contract.contract_num }}</a></td>
					<td>{{ contract.client }}</td>
					<td>{{ contract.begin_date|date:"Y-m-d" }}</td>
					<td>{{ contract.end_date|date:"Y-m-d" }}</td>
					<td>{{ contract.month_pay }}</td>
					<td>{{ contract.flag }}</td>
				<tr>
				{% endfor %}
			</table>
		{% else %}
			{% if query %}
				<span class="help-block">搜索了包含"{{ query }}"的客户名;无结果。</span>
			{% endif %}
		{% endif %}

{% endblock %}

rent/templates/rent/search_pr.html
{% extends "base.html" %}
{% block title %}搜索缴费记录{% endblock %}

	{% block search_bar %}
		<form method="get" action="" class="form-search">
			<input type="text" name="name" id="" placeholder="按客户名搜索缴费记录" class="input-media search-query"/>
			<input type="submit" value="提交" class="btn"/>
		</form>
	{% endblock  %}
{% block content%}
		{% if results %}
			<span class="help-block">搜索了客户名包含"{{ query }}"的所有缴费记录;结果列表如下。</span>

			<table class="table table-bordered table-striped table-hover">
				<thead>
				<th>缴费时间</th>
				<th>租户姓名</th>
				<th>缴费金额</th>
				<th>所属合同编号</th>
				<th>租约起始时间</th>
				<th>租约终止时间</th>
				</thead>
				{% for record in results %}
				<tr>
				<td>{{ record.pay_date|date:"Y-m-d" }}</td>
				<td>{{ record.contract.client }}</a> </td>
				<td>{{ record.pay_value}}</td>
				<td><a href="{{ record.contract.get_absolute_url }}">{{ record.contract.contract_num }}</td>
				<td>{{ record.contract.begin_date|date:"Y-m-d" }}</td>
				<td>{{ record.contract.end_date|date:"Y-m-d" }}</td>
				</tr>
				{% endfor %}
			</table>
		{% else %}
			{% if query %}
			<span class="help-block">搜索了包含"{{ query }}"的客户名;无结果。</span>
			{% endif %}
		{% endif %}
{% endblock %}